### PR TITLE
proc/native: acquire debug programs privilege on Windows

### LINKED ISSUE #3136: delve can not attach to process owned by other user on windows
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
  Delve Debugger
  Version: 1.9.1
  Build: $Id: d81b9fd12bfa603f3cf7a4bc842398bd61c42940 $
2. What version of Go are you using? (`go version`)?
  go version go1.19.1 windows/amd64
3. What operating system and processor architecture are you using?
   windows 10
   amd64
4. What did you do?
  i want to debug a service of windows. i want to attach the process of windows service by delve. but delve give a error:
   when i run C:\Projects\wireguard-windows>dlv attach 10026 . it outputs:
    "could not attach to pid 10026: Access is denied."
5. What did you expect to see?
  i expect delve attach success.
6. What did you see instead?
  windbg can attach the process of windows service

### PR DESCRIPTION
**Pull request by aarzilli**
On Windows we need to acquire the SeDebugPrivilege privilege to be able
to debug programs owned by different users.

See:

https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/debug-privilege

This procedure will fail if the current user does not have this
privilege so do not complain too much about it.

Fixes #3136

### CODE REVIEW

File: pkg/proc/native/proc_windows.go [hunk 1]
```diff
@@ -141,15 +141,30 @@ func findExePath(pid int) (string, error) {
 	}
 }
 
+var debugPrivilegeAcquired = false
```
Comment (derekparker) [inline pkg/proc/native/proc_windows.go:144]: nit: s/debugPrivilegeAcquired/debugPrivilegeRequested/

I know this is a nit but technically we're not certain to have acquired this permission, only certain that we've requested it.

Comment (aarzilli) [reply pkg/proc/native/proc_windows.go]: Done.

**Review by derekparker — APPROVED** [review]
LGTM
