### PR TITLE
proc: add regression test for issue #3548

### LINKED ISSUE #3548: E08 during memory read for packet
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

If this is about source listing not showing up (or breakpoints not being
accepted) while running in a container please read our
[FAQ](https://github.com/go-delve/delve/blob/master/Documentation/faq.md#substpath)
first.

1. What version of Delve are you using (`dlv version`)?
```
❯ dlv version
Delve Debugger
Version: 1.21.2
Build: $Id: 98f8ab2662d926245917ade2f2bb38277315c7fc $
```
2. What version of Go are you using? (`go version`)?
```
❯ go version
go version go1.21.1 darwin/amd64
```
3. What operating system and processor architecture are you using?
```
macOS Sonoma 14.1 amd64
```
4. What did you do?
When trying to debug a test that contains a struct with a non-pointer object that has a function with a pointer receiver defined, interacting with that object causes all locals to return `unreadable could not read string pointer protocol error E08 during memory read for packet`.

Steps:
```
b TestHi:13
c
p c
```
5. What did you expect to see?
I expected to able to print values for locals.
6. What did you see instead?
I see all values being returned as error E08.

Log file and files to reproduce error are [here](https://gist.github.com/dhoizner/d728ca57bfd3a4cf1ebc287bc96ce8f7).

Changing `Thing` to be `*Thing`  on [line 11](https://gist.github.com/dhoizner/d728ca57bfd3a4cf1ebc287bc96ce8f7#file-foo_test-go-L11) resolves the error.

### PR DESCRIPTION
**Pull request by aarzilli**
Issue #3548 describes a bug in the compiler which was fixed by commit
505e50b. But this case wasn't covered by our current tests (obviously)
and the fix in the compiler looks accidental so it's worth adding a
test for it.

Fixes #3548

### CODE REVIEW

File: pkg/proc/variables_test.go [hunk 1]
```diff
@@ -1722,3 +1722,20 @@ func TestBadUnsafePtr(t *testing.T) {
 		}
 	})
 }
+
+func TestCapturedVariable(t *testing.T) {
+	if !goversion.VersionAfterOrEqual(runtime.Version(), 1, 22) {
+		t.Skip("broken")
```
Comment (derekparker) [inline pkg/proc/variables_test.go:1728]: Can you add more context here, like `broken in versions prior to 1.22 due to a compiler bug`. Also, does this affect all versions < 1.22 or was the bug introduced in 1.21 and we didn't catch it? If the latter, we should be more specific in the skip.

Finally, can you add a link to the Github issue in a comment somewhere for more context.

Comment (aarzilli) [reply pkg/proc/variables_test.go:1731]: Done. I hadn't checked before but it really is a regression in 1.21.

**Review by derekparker — APPROVED** [review]
LGTM

**Comment by balleriniGsped** [comment]
sill facing this bug with GO 1.25.1 on darwin/amd64, se issue #3548
