### PR TITLE
Shorten variable types

### LINKED ISSUE #3516: dap: strip package paths from variable types
Now that we strip paths from function names in the stacktrace view (since #3500), I want the same for the types of variables in the variables view.

Here's a simple example. With a reasonably sized side bar, I can't see any variable names or values, only the beginnings of the paths:
image

This is how ridiculously wide I would have to make the side bar so that I can see variable names and values (impractical on a laptop screen):
image

This is what I would like to see instead:
image

I'd be interested in working on this, but it looks a lot less straighforward than #3500 was, so I'd need some guidance.

### PR DESCRIPTION
**Pull request by stefanhaller**
The variables view in VS Code is a lot easier to read if long type names are
shortened in much the same way as we shorten them for functions in the call
stack view.

We only shorten them in the value strings; the Type field of dap.Variable is
kept as is. Since this only appears in a tooltip, it isn't a problem to have the
full type visible there.

Fixes #3516.

### CODE REVIEW

File: service/api/prettyprint.go [hunk 1]
```diff
@@ -21,33 +21,48 @@ const (
 // SinglelineString returns a representation of v on a single line.
 func (v *Variable) SinglelineString() string {
 	var buf bytes.Buffer
-	v.writeTo(&buf, true, false, true, "", "")
+	v.writeTo(&buf, true, false, true, false, "", "")
+	return buf.String()
+}
+
+// SinglelineStringWithShortTypes returns a representation of v on a single line, with types shortened.
+func (v *Variable) SinglelineStringWithShortTypes() string {
```
Comment (stefanhaller) [inline service/api/prettyprint.go:29]: I decided to add a new function instead of adding a flag to `SinglelineString`, as that function has tons of call sites that I would have had to adapt.

File: service/api/prettyprint.go [hunk 2]
```diff
@@ -21,33 +21,48 @@ const (
...
-func (v *Variable) writeTo(buf io.Writer, top, newlines, includeType bool, indent, fmtstr string) {
+func (v *Variable) typeStr(shortenType bool) string {
+	if shortenType {
+		return ShortenType(v.Type)
+	}
+
+	return v.Type
+}
+
+func (v *Variable) writeTo(buf io.Writer, top, newlines, includeType, shortenType bool, indent, fmtstr string) {
```
Comment (stefanhaller) [inline service/api/prettyprint.go:57]: I also considered turning the `includeType` bool into an enum with three values (off, short, full). That didn't work well though, because of the way includeType is negated sometimes.

**Review by stefanhaller — COMMENTED** [review]
I haven't had a lot of time yet to test this thoroughly, but a cursory test makes this look very promising.

Putting it out there so that others can play with it. I'll be on vacation for two weeks now.

File: service/api/prettyprint.go (hunk 1 above)
Comment (aarzilli) [reply service/api/prettyprint.go:29]: SinglelineStringFormatted as very few calls.

**Review by aarzilli — COMMENTED** [review]
There isn't going to be any kind of configuration to turn this off?

File: service/api/prettyprint.go (hunk 2 above)
Comment (aarzilli) [reply service/api/prettyprint.go:57]: I think having four booleans on a row crosses a threshold. If @derekparker agrees I would rebase this on something like this https://github.com/go-delve/delve/pull/3536

**Comment by stefanhaller** [comment]
> There isn't going to be any kind of configuration to turn this off?

I don't think it needs to be configurable, I really can't imagine why anybody would want to see the long types. We didn't make #3500 configurable either, and I think this is very similar. Also, you can see the full type in a tooltip by hovering over a variable name.

File: service/api/prettyprint.go (hunk 2 above)
Comment (stefanhaller) [reply service/api/prettyprint.go:57]: That would be fine with me. I suppose I'd wait until that PR is merged and then rebase on master? There's no rush, I'm now on vacation for two weeks, so can only continue with this after I'm back anyway.

**Comment by aarzilli** [comment]
> why anybody would want to see the long types

Because short ones could be ambiguous. But if they are visible on hover it's probably ok.

File: service/api/prettyprint.go (hunk 1 above)
Comment (stefanhaller) [reply service/api/prettyprint.go:51]: Do you mean I should use `SinglelineStringFormatted` instead of adding `SinglelineStringWithShortTypes`? If so, should I change its behavior to always shorten types, or add a bool parameter to it to make it configurable? Personally I'd find it preferable to add the new function, as I don't need the ability to pass a format string.

**Comment by stefanhaller** [comment]
Sorry for the delay, I was on vacation.

I rebased this onto master, I'm quite happy about how much cleaner the change is now. Can you please have another look?

**Review by aarzilli — APPROVED** [review]
LGTM

**Comment by aarzilli** [comment]
cc @hyangah @suzmue you wanted to review this I think.

**Review by suzmue — APPROVED** [review]
LGTM. Thanks @stefanhaller!!
