### PR TITLE
godwarf: fix nil pointer reading recursive types involving an array

### LINKED ISSUE #1578: Internal debugger error when print variable has recursive type
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $
```

2. What version of Go are you using? (`go version`)?
```
go version go1.12.5 linux/amd64
```

3. What operating system and processor architecture are you using?

```
Linux instance-1 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
```

4. What did you do?
Debug program has recursive type.

**sample.go**

```go
package main

type Cache struct { // see cmd/compile/internal/ssa/cache.go
	blocks [2000]Block
}

type Block struct { //
	cache *Cache
}

func main() {
	var b Block
	_ = b
}
```

```
$ dlv debug sample.go
(dlv) b main.main
(dlv) c
(dlv) n
(dlv) p b
Command failed: Internal debugger error: runtime error: invalid memory address or nil pointer dereference
runtime.gopanic (0x42d6a4)
        /home/osamu_nakamura/go/src/runtime/panic.go:522
runtime.panicmem (0x442740)
        /home/osamu_nakamura/go/src/runtime/panic.go:82
runtime.sigpanic (0x44256f)
        /home/osamu_nakamura/go/src/runtime/signal_unix.go:390
github.com/go-delve/delve/pkg/dwarf/godwarf.(*TypedefType).sizeIntl (0x67843f)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:436
github.com/go-delve/delve/pkg/dwarf/godwarf.(*TypedefType).Size (0x6783a8)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:428
github.com/go-delve/delve/pkg/dwarf/godwarf.readType (0x67aaaf)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:597
github.com/go-delve/delve/pkg/dwarf/godwarf.readType.func2 (0x67c5f1)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:558
github.com/go-delve/delve/pkg/dwarf/godwarf.readType (0x678ff0)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:742
github.com/go-delve/delve/pkg/dwarf/godwarf.readType.func2 (0x67c5f1)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:558
github.com/go-delve/delve/pkg/dwarf/godwarf.readType (0x67b91a)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:947
github.com/go-delve/delve/pkg/dwarf/godwarf.readType.func2 (0x67c5f1)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:558
github.com/go-delve/delve/pkg/dwarf/godwarf.readType (0x67b011)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:877
github.com/go-delve/delve/pkg/dwarf/godwarf.readType.func2 (0x67c5f1)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:558
github.com/go-delve/delve/pkg/dwarf/godwarf.readType (0x678ff0)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:742
github.com/go-delve/delve/pkg/dwarf/godwarf.readType.func2 (0x67c5f1)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:558
github.com/go-delve/delve/pkg/dwarf/godwarf.readType (0x67b91a)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:947
github.com/go-delve/delve/pkg/dwarf/godwarf.ReadType (0x678920)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/dwarf/godwarf/type.go:483
github.com/go-delve/delve/pkg/proc.(*Image).Type (0x6ddf11)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/proc/bininfo.go:685
github.com/go-delve/delve/pkg/proc.readVarEntry (0x6ddee3)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/proc/variables.go:1017
github.com/go-delve/delve/pkg/proc.(*EvalScope).extractVarInfoFromEntry (0x6de1fa)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/proc/variables.go:1036
github.com/go-delve/delve/pkg/proc.(*EvalScope).Locals (0x6e6c33)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/proc/variables.go:2253
github.com/go-delve/delve/pkg/proc.(*EvalScope).evalIdent (0x6ac343)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/proc/eval.go:596
github.com/go-delve/delve/pkg/proc.(*EvalScope).evalAST (0x6a85cf)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/proc/eval.go:191
github.com/go-delve/delve/pkg/proc.(*EvalScope).EvalExpression (0x6a6b47)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/proc/eval.go:38
github.com/go-delve/delve/pkg/proc.(*EvalScope).EvalVariable (0x7495ad)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/pkg/proc/variables.go:776
github.com/go-delve/delve/service/debugger.(*Debugger).EvalVariableInScope (0x749569)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/service/debugger/debugger.go:911
github.com/go-delve/delve/service/rpc2.(*RPCServer).Eval (0x923435)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/service/rpc2/server.go:447
reflect.Value.call (0x4b41d0)
        /home/osamu_nakamura/go/src/reflect/value.go:447
reflect.Value.Call (0x4b3c53)
        /home/osamu_nakamura/go/src/reflect/value.go:308
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func2 (0x92b06c)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/service/rpccommon/server.go:318
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).serveJSONCodec (0x929550)
        /home/osamu_nakamura/.local/go/src/github.com/go-delve/delve/service/rpccommon/server.go:320
runtime.goexit (0x45a610)
        /home/osamu_nakamura/go/src/runtime/asm_amd64.s:1337

```

5. What did you expect to see?

print b variable.

6. What did you see instead?

Internal debugger error occured.

----

When `godwarf.readType()` read `type Block`, it creates TypedefType object for `type Block` and stores it in to `typeCache`, then starts to scan fields of struct in order to fill `t.Type` field.
At this point, `typeCache` has a cache for `type Block`, however t.Type is nil.

When field scanning reaches `Cache.blocks`, readType() uses cache in typeCache, but initialization of t.Type hasn't been finished yet (i.e. t.Type is nil).

### PR DESCRIPTION
**Pull request by aarzilli**
```
godwarf: fix nil pointer reading recursive types involving an array

Fixes #1578

```

### CODE REVIEW

File: _fixtures/testvariables2.go [hunk 1]
```diff
@@ -93,6 +93,14 @@ type truncatedMap struct {
 	v []map[string]astruct
 }
 
+type Cache struct { // see cmd/compile/internal/ssa/cache.go
+	blocks [2000]Block
+}
+
+type Block struct { //
```
Comment (derekparker) [inline _fixtures/testvariables2.go]: Extra comment?

Comment (aarzilli) [reply _fixtures/testvariables2.go]: Yes, copypasted from issue.
