### PR TITLE
proc: use CPUID to determine ZMM_Hi256 region offset

### LINKED ISSUE #3827: TestClientServer_FpRegisters fails for XMM12 registers
1. What version of Delve are you using (`dlv version`)?
   1.23.1
2. What version of Go are you using? (`go version`)?
   1.23.1
3. What operating system and processor architecture are you using?
   Debian sid. amd64. 4th generation EPYC processors from AMD
4. What did you do?
   Package delve for Debian and run the tests during build.
5. What did you expect to see?
   No error.
6. What did you see instead?
```
     integration2_test.go:1806: register XMM12 expected to contain "…[ZMM12hl] 0x3ff66666666666663ff4cccccccccccd" got "0x3ff66666666666663ff4cccccccccccd\tv2_int={ 3ff4cccccccccccd 3ff6666666666666 }\tv4_int={ cccccccd 3ff4cccc 66666666 3ff66666 }\tv8_int={ cccd cccc cccc 3ff4 6666 6666 6666 3ff6 }\tv16_int={ cd cc cc cc cc cc f4 3f 66 66 66 66 66 66 f6 3f }\tv2_float={ 1.3 1.4 }\tv4_float={ -1.07374184e+08 1.9124999 2.720083e+23 1.925 }\n\t[YMM12h] 0x3ff66666666666663ff4cccccccccccd\tv2_int={ 3ff4cccccccccccd 3ff6666666666666 }\tv4_int={ cccccccd 3ff4cccc 66666666 3ff66666 }\tv8_int={ cccd cccc cccc 3ff4 6666 6666 6666 3ff6 }\tv16_int={ cd cc cc cc cc cc f4 3f 66 66 66 66 66 66 f6 3f }\tv2_float={ 1.3 1.4 }\tv4_float={ -1.07374184e+08 1.9124999 2.720083e+23 1.925 }\n\t[ZMM12hl] 0x00000000000000000000000000000000\tv2_int={ 0000000000000000 0000000000000000 }\tv4_int={ 00000000 00000000 00000000 00000000 }\tv8_int={ 0000 0000 0000 0000 0000 0000 0000 0000 }\tv16_int={ 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 }\tv2_float={ 0 0 }\tv4_float={ 0 0 0 0 }\n\t[ZMM12hh] 0x00000000000000000000000000000000\tv2_int={ 0000000000000000 0000000000000000 }\tv4_int={ 00000000 00000000 00000000 00000000 }\tv8_int={ 0000 0000 0000 0000 0000 0000 0000 0000 }\tv16_int={ 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 }\tv2_float={ 0 0 }\tv4_float={ 0 0 0 0 }"

```

It's reported at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082973
Full log https://people.debian.org/~sanvila/build-logs/202409/delve_1.23.1-1_amd64-20240929T101703.749Z

Unfortunately I don't have CPU with AVX512, so I can't confirm the failure myself.

### PR DESCRIPTION
**Pull request by jiegec**
The offset of state component i can be found via
CPUID.(EAX=0DH,ECX=i):EBX. The ZMM_Hi256 is state component 6, so we use CPUID to enumerate the offset instead of hardcoding.

Fixes #3827.

### CODE REVIEW

**Review by aarzilli — COMMENTED** [review]
We can't do this. AMD64XstateRead is also used to decode registers read from core files, we can not assume that the CPU we are running on produced them.

I think the starting offset for the ZMMhi256 region should be taken as an input parameter, the calls to this function in pkg/proc/native can then call AMD64XstateZMMHi256Offset.
The calls in pkg/proc/core should pass 0 as a parameter and, in that case, this function will have to do something like gdb does in https://github.com/bminor/binutils-gdb/blob/df89bdf0baf106c3b0a9fae53e4e48607a7f3f87/gdb/i387-tdep.c#L916

**Review by aarzilli — APPROVED** [review]

File: pkg/proc/amd64util/xsave_amd64.go [hunk 1]
```diff
@@ -28,3 +28,28 @@ func AMD64XstateMaxSize() int {
 	})
 	return xstateMaxSize
 }
+
+var xstateZMMHi256Offset int
+var loadXstateZMMHi256OffsetOnce sync.Once
+
+// Probe ZMM_Hi256 offset of the current CPU.  Beware that core dumps may be
```
Comment (aarzilli) [inline pkg/proc/amd64util/xsave_amd64.go:35]: This comment needs to start with AMD64XstateZMMHi256Offset.

Comment (jiegec) [reply pkg/proc/amd64util/xsave_amd64.go]: Fixed

**Comment by aarzilli** [comment]
The build fails on freebsd:

```
pkg/proc/native/ptrace_freebsd_amd64.go:76:55: not enough arguments in call to amd64util.AMD64XstateRead
	have ([]byte, bool, *amd64util.AMD64Xstate)
	want ([]byte, bool, *amd64util.AMD64Xstate, int)
```

and on linux/386:

```
pkg/proc/native/ptrace_linux_386.go:41:55: not enough arguments in call to amd64util.AMD64XstateRead
     have ([]byte, bool, *amd64util.AMD64Xstate)
     want ([]byte, bool, *amd64util.AMD64Xstate, int)
```

**Review by aarzilli — APPROVED** [review]
LGTM, thanks.

**Review by derekparker — APPROVED** [review]
LGTM
