### PR TITLE
dwarf/frame: discard indirect flag reading personality func in eh_frame

### LINKED ISSUE #3015: Could not parse .eh_frame section: pointer encoding not supported
1. What version of Delve are you using (`dlv version`)?

```
Delve Debugger
Version: 1.8.2
Build: 65e03d673d31f9a6c9c2bd187a4ff2219444b16f
```

2. What version of Go are you using? (`go version`)?

```
go1.18.2 linux/amd64
```

3. What operating system and processor architecture are you using?

Ubuntu 20.04.4 LTS, Ubuntu 22.04 LTS

4. What did you do?

Debugged a program and got the error: `debugger error loading binary "/lib/x86_64-linux-gnu/libc.so.6": could not parse .eh_frame section: pointer encoding not supported 0x9b at 0x59f4`.

Is there a ticket for such a support? Is it possible to work around the error?

### PR DESCRIPTION
**Pull request by aarzilli**
We don't do anything with the personality function so there is no point
in complaining that we don't fully support the pointer encoding flags
used to describe it.

This matches the current level of support of pointer encodings in gdb
(they are discarded when reading the personality function and not
supported for FDEs because gcc doesn't generate them).

Fixes #3015

### CODE REVIEW

File: pkg/dwarf/frame/entries.go [hunk 1]
```diff
@@ -142,7 +144,7 @@ func (ptrEnc ptrEnc) Supported() bool {
 			// These values aren't defined at the moment
 			return false
 		}
-		if ptrEnc&0xf0 != ptrEncPCRel {
+		if (ptrEnc&0xf0)&^ptrEncSupportedFlags != 0 {
```
Comment (derekparker) [inline pkg/dwarf/frame/entries.go:147]: While we're touching this code, can we assign the integer immediate values to constants and explain their usage.

Comment (aarzilli) [reply pkg/dwarf/frame/entries.go]: Done.
