### PR TITLE
service/dap: reject most requests before launch/attach

### LINKED ISSUE #4237: service/dap: telemetry report: nil pointer dereference in onStepOutRequest
```
#!stacks
"runtime.gopanic" && "dap.(*Session).stepUntilStopAndNotify" && "dap.(*Session).onStepOutRequest"
```
Issue created by [stacks](https://pkg.go.dev/golang.org/x/telemetry/cmd/stacks).

This stack `RlW5Lg` was [reported by telemetry](https://telemetry.go.dev/data/2026-01-13):

- `delve/bug`
- [`github.com/go-delve/delve/service/dap.(*Session).recoverPanic:+2`](https://github.com/go-delve/delve/blob/v1.25.2/service/dap/server.go#L583)
- [`runtime.gopanic:+50`](https://cs.opensource.google/go/go/+/go1.25.1:src/runtime/panic.go;l=783)
- `runtime.panicmem:=262`
- [`runtime.sigpanic:+9`](https://cs.opensource.google/go/go/+/go1.25.1:src/runtime/signal_windows.go;l=393)
- [`internal/sync.(*Mutex).Lock:=63`](https://cs.opensource.google/go/go/+/go1.25.1:src/internal/sync/mutex.go;l=63)
- [`sync.(*Mutex).Lock:=46`](https://cs.opensource.google/go/go/+/go1.25.1:src/sync/mutex.go;l=46)
- [`github.com/go-delve/delve/service/debugger.(*Debugger).Command:+20`](https://github.com/go-delve/delve/blob/v1.25.2/service/debugger/debugger.go#L1082)
- [`github.com/go-delve/delve/service/dap.(*Session).stepUntilStopAndNotify:+2`](https://github.com/go-delve/delve/blob/v1.25.2/service/dap/server.go#L2109)
- [`github.com/go-delve/delve/service/dap.(*Session).onStepOutRequest:+2`](https://github.com/go-delve/delve/blob/v1.25.2/service/dap/server.go#L2052)
- [`github.com/go-delve/delve/service/dap.(*Session).handleRequest.func5:+2`](https://github.com/go-delve/delve/blob/v1.25.2/service/dap/server.go#L735)
- `runtime.goexit:+0`
```
github.com/go-delve/delve/cmd/dlv@v1.25.2 go1.25.1 windows/amd64 (1)
```

Use this command to reproduce the executable:
`(HOME=$(mktemp -d); GOOS=windows GOARCH=amd64 GOTOOLCHAIN=go1.25.1 go install github.com/go-delve/delve/cmd/dlv@v1.25.2 && find $HOME/go/bin -type f)`
To disassemble: `go tool objdump exe | less`

### PR DESCRIPTION
**Pull request by aarzilli**
Reject most requests until a launch/attach command has succeeded.

Fixes #4237

### CODE REVIEW

File: service/dap/server.go [hunk 1]
```diff
@@ -763,6 +763,14 @@ func (s *Session) handleRequest(request dap.Message) {
 		return
 	}
 
+	// Reject all other requests if the target hasn't been launched
+	if s.debugger == nil {
+		r := request.(dap.RequestMessage).GetRequest()
+		//s.sendErrorResponse(*r, NoDebugIsRunning, "not running", "not running")
```
Comment (derekparker) [inline service/dap/server.go]: Remove leftover comment.

**Review by derekparker — APPROVED** [review]
LGTM

File: service/dap/server.go (hunk 1 above)
Comment (aarzilli) [reply service/dap/server.go]: Done.
