### PR TITLE
pkg/proc/core: add error details when reading spliced memory

### LINKED ISSUE #1700: Command failed: EOF
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?

Version: 1.3.0

2. What version of Go are you using? (`go version`)?
go version go1.13 linux/amd64

3. What operating system and processor architecture are you using?

4. What did you do?
dlv core ./newscenter core.26945
(dlv) goroutines
Command failed: EOF

5. What did you expect to see?

6. What did you see instead?

### PR DESCRIPTION
**Pull request by chainhelen**
The origin error message is confusing, so add some details.

Fixes #1700   

-----   

I not sure whether the change is reasonable. So I will close this pr if disagree.   

-----   

This [ci](https://ci.appveyor.com/project/derekparker/delve-facy3/builds/27721539) failed, but it doesn't seem to have anything to do with my changes.

### CODE REVIEW

File: pkg/proc/core/core.go [hunk 1]
```diff
@@ -113,8 +113,11 @@ func (r *SplicedMemory) ReadMemory(buf []byte, addr uintptr) (n int, err error)
 		}
 		pn, err := entry.reader.ReadMemory(pb, addr)
 		n += pn
-		if err != nil || pn != len(pb) {
-			return n, err
+		if err != nil {
+			return n, fmt.Errorf("an error occurred when reading spliced memory at 0x%x, the error message is %s", addr, err)
```
Comment (aarzilli) [inline pkg/proc/core/core.go]: `fmt.Errorf("error while reading spliced memory at %#x: %v", addr, err)`

**Comment by chainhelen** [comment]
Thx. Done and rebase.
