### PR TITLE
pkg/proc,service,pkg/terminal: add stacktrace caching

### LINKED ISSUE #989: Allow to load the full stacktrace
For better visual debuggers will be cool to have an ability to load the whole stack trace without setting the depth.
Right now we should pass it through the API deep to proc.stacktrace function.

@derekparker What do you think?

Original request – https://youtrack.jetbrains.com/issue/GO-3995

### LINKED ISSUE #3809: Navigating the stack in a coredump resulting from a stack overflow is slow
I was debugging a coredump produced by a stack overflow recently, and I noticed that Delve gets increasingly slower as I go up the stack. I suspect that stack navigation commands in Delve (`up`, `down` etc) could be linear in stack size. Does that sound right? 

I usually need to go to the top of the stack to understand what caused the stack overflow, and that easily takes minutes, because each step along the stack is slow (and is only getting slower).

I assume this should be fairly easy to reproduce, but let me know if you need more details.

---

1. What version of Delve are you using (`dlv version`)?
  
   1.23.0
2. What version of Go are you using? (`go version`)?

   go1.23-20240626-RC01

3. What operating system and processor architecture are you using?

   Linux, x64

### PR DESCRIPTION
**Pull request by aarzilli**
Adds caching to stacktraces so that stacktrace requests are not
quadratic. Also add a Skip parameter to the Stacktrace RPC request so
that clients can only request the frames they need.

Fixes #3809
Fixes #989

### CODE REVIEW

**Comment by aarzilli** [comment]
The test failure on darwin/amd64 looks like it could be related, I'll have to look into it first.

File: pkg/proc/stack.go [hunk 1]
```diff
@@ -165,17 +179,30 @@ const (
 // GoroutineStacktrace returns the stack trace for a goroutine.
 // Note the locations in the array are return addresses not call addresses.
 func GoroutineStacktrace(tgt *Target, g *G, depth int, opts StacktraceOptions) ([]Stackframe, error) {
+	if opts == 0 {
```
Comment (derekparker) [inline pkg/proc/stack.go:182]: Would it make sense to include `opts` in the cache key to be able to cache these calls as well?

File: pkg/proc/stack.go [hunk 2]
```diff
@@ -385,11 +412,16 @@ func (it *stackIterator) newStackframe(ret, retaddr uint64) Stackframe {
...
 
-func (it *stackIterator) stacktrace(depth int) ([]Stackframe, error) {
+func (it *stackIterator) stacktrace(depth int, initialFrames []Stackframe) ([]Stackframe, error) {
 	if depth < 0 {
 		return nil, errors.New("negative maximum stack depth")
 	}
-	frames := make([]Stackframe, 0, depth+1)
+	var frames []Stackframe
+	if len(initialFrames) > 0 {
+		frames = initialFrames
```
Comment (derekparker) [inline pkg/proc/stack.go:425]: Couldn't we return early here if `len(frames) >= depth`? I know that `it.stacktraceFunc` will return pretty quickly in this case, so maybe it's not worth it here.

File: pkg/proc/stack.go (hunk 1 above)
Comment (aarzilli) [reply pkg/proc/stack.go:182]: The only way where we do a stacktrace with non-default options is if a user asks for a stacktrace at the command line by passing a bunch of arguments to the `stack` command. I don't think we would get to reuse that cache, so I don't think it's worth it.

File: pkg/proc/stack.go (hunk 2 above)
Comment (aarzilli) [reply pkg/proc/stack.go:425]: Done.

File: pkg/proc/stack.go (hunk 1 above)
Comment (derekparker) [reply pkg/proc/stack.go:182]: Ack.

File: pkg/proc/stack.go (hunk 2 above)
Comment (derekparker) [reply pkg/proc/stack.go:425]: We should slice `frames[:depth+1]` before returning, no?

Comment (aarzilli) [reply pkg/proc/stack.go:425]: No, if we did the callers of `stacktrace` would cache the truncated version. The contract of the stacktrace functions was always that they could return more than the requested depth, because of inline expansion, so everything should be fine.

The truncation to the requested depth is done by the rpc call, when it matters (sending more would be expensive). DAP already did its own truncation before so nothing to change there.
