### PR TITLE
terminal: add prompt when breakpoint is hit during next/step/stepout

### LINKED ISSUE #2317: pkg/terminal: add option to disable auto-continue during next/step/stepout
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
```
localhost:~ xxx$ dlv version
Delve Debugger
Version: 1.2.0
Build: 86d4b0b9915d55833a99bfb4c8b3a138f03ab802
localhost:~ xxx$ 
```

2. What version of Go are you using? (`go version`)?
```
localhost:~ xxx$ go version
go version go1.12.8 darwin/amd64
localhost:~ xxx$ 
```

3. What operating system and processor architecture are you using?
```
localhost:~ xxx$ uname -a
Darwin Hanss-MacBook-Pro.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
localhost:~ xxx$ sysctl -a | grep machdep.cpu 
machdep.cpu.max_basic: 20
machdep.cpu.max_ext: 2147483656
machdep.cpu.vendor: GenuineIntel
machdep.cpu.brand_string: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
machdep.cpu.family: 6
machdep.cpu.model: 61
localhost:~ xxx$ 
```

4. What did you do?
```Golang
// file main.go
package main

import (
	"time"
)

func main() {
	go b()
	time.Sleep(time.Second)
	time.Sleep(time.Second)
}

func b() {
	time.Sleep(time.Second)    // breakpoint  2
}
```

```
localhost:~ xxx$ dlv debug main.go
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x105882f for main.main() ./main.go:7
(dlv) b main.b
Breakpoint 2 set at 0x105888f for main.b() ./main.go:13
(dlv) c
(dlv) n
```
In main func, repeat `n` command.

5. What did you expect to see?
After some one particular `n` command, dlv stops at breakpoint 2.

6. What did you see instead?

The dlv debugger didn't catch breakpoint 2.

Will dlv switch goroutine automatically to catch breakpoints on different goroutines?   I found gdb works as expected.

### PR DESCRIPTION
**Pull request by aarzilli**
Adds a prompt asking the user what to do when a breakpoint is hit on a
different goroutine while next/step/stepout is being executed.

Gives the user the opportunity to cancel next/step/stepout, continue
once skipping the breakpoint or automatically skipping all other
concurrent breakpoints until next/step/stepout is finished.

Fixes #2317

### CODE REVIEW

File: pkg/terminal/command.go [hunk 1]
```diff
@@ -1454,6 +1474,20 @@ func continueUntilCompleteNext(t *Term, state *api.DebuggerState, op string, sho
 	}
 }
 
+func promptAutoContinue(t *Term, op string) (string, error) {
+	for {
+		answer, err := t.line.Prompt(fmt.Sprintf("[c] continue [s] stop her and cancel %s, [f] finish %s skipping all breakpoints? ", op, op))
```
Comment (derekparker) [inline pkg/terminal/command.go:1479]: s/her/here/

**Review by derekparker — CHANGES_REQUESTED** [review]
One minor typo change.

File: pkg/terminal/command.go [hunk 2]
```diff
@@ -1436,8 +1436,28 @@ func continueUntilCompleteNext(t *Term, state *api.DebuggerState, op string, sho
 		}
 		return nil
 	}
+	autoContinue := false
```
Comment (polinasok) [inline pkg/terminal/command.go:1439]: suggest renaming to skipBreakpoints

File: pkg/terminal/command.go (hunk 1 above)
Comment (polinasok) [reply pkg/terminal/command.go:1479]: It is not clear that "continue" will hit the internal breakpoint (unless it counters others along the way). Maybe "continue %s hitting all breakpoints"?

Comment (aarzilli) [reply pkg/terminal/command.go]: > s/her/here/

Done.

> It is not clear that "continue" will hit the internal breakpoint (unless it counters others along the way). Maybe "continue %s hitting all breakpoints"?

That makes it sound like it does the same thing as 'finish' IMO. It would have to be "continue and try to finish %s but repeat this prompt if a breakpoint is hit" but I think that's too verbose. I think just saying 'continue' here is fine, there's three options and with the other two it should be immediately obvious whether they are right or wrong, it should be clear by exclusion if you want 'continue' and it's a safe option to experiment with.

File: pkg/terminal/command.go (hunk 2 above)
Comment (aarzilli) [reply pkg/terminal/command.go]: Done.

File: pkg/terminal/command.go (hunk 1 above)
Comment (derekparker) [reply pkg/terminal/command.go]: I agree with @aarzilli here that the wording as is should be ok for users. If we get reports on confusion from a UX perspective we can reevaluate.

**Review by derekparker — APPROVED** [review]
LGTM

File: pkg/terminal/command.go (hunk 1 above)
Comment (polinasok) [reply pkg/terminal/command.go]: That's fair.
Also, this could be explained in more detail in the documentation without polluting the prompt.

**Review by polinasok — APPROVED** [review]
