### PR TITLE
terminal/colorize: list command avoid printing multiple dup `package` string

### LINKED ISSUE #2896: `list` command prints multiple `package` string by multiple colorToks with type token.Illegal
Please answer the following before submitting your issue: 

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

Here is an test code (main.go):

```
package main

// Vehical defines the vehical behavior
type Vehical interface {
	// Run vehical can run in a speed
	Run()
}

// BMWS1000RR defines the motocycle bmw s1000rr
type BMWS1000RR struct {
}

// Run bwm s1000rr run
func (a *BMWS1000RR) Run() {
	println("I can run at 300km/h")
}

func main() {
	var vehical = &BMWS1000RR{}
	vehical.Run()
}
```

Then run `dlv debug main.go` and `list main.go:0`:

```
$ dlv debug main.go 
Type 'help' for list of commands.
(dlv) l main.go:0
Showing /Users/zhangjie/gotest/main.go:0 (PC: 0x0)
     1:	packagepackage main
     2:	
     3:	// Vehical defines the vehical behavior
     4:	type Vehical interface {
     5:		// Run vehical can run in a speed
(dlv) exit
```

1. What version of Delve are you using (`dlv version`)?
   Delve Debugger
   Version: 1.8.0
   Build: $Id: 6a6c9c332d5354ddf1f8a2da3cc477bd18d2be53 $
   
   I build from master branch, commit: e3f4c40b
2. What version of Go are you using? (`go version`)?
    go version go1.16.3 darwin/amd64
3. What operating system and processor architecture are you using?
    darwin and amd64
4. What did you do?
    I wanted to test the terminal/colorize.Print function to highlight the source code, but accidently found that the `list` command has problems. It should output `package` rather than `packagepackage`.
5. What did you expect to see?
   `list main.go:0` outputs `package main` instead of `packagepackage main`.
6. What did you see instead?
   `list main.go:0` outputs `packagepackage main`.

---

Here  there's an typo error  in ast.Inspect(fset, func(*ast.Node)) to generate colorToks, "Pacakge" should be "Package". After I fixed this typo error, `list` will outputs `packagepackagepackage main`.

After checking the code of ast.Node and its implentions (especially ast.File and Ast.FuncType), I find that there's some occassions token's start position maybe token.NoPos. For example, the interface method `Vehical.Run()` method here. Dlv will generate a colorToken(token.Illegal, 0, 7) for this method. While linewriter outputs, it'll output a `package` string for this. ast.File will cause the same problem which outputs another `package` string.

If we check ast.File to emit the `package` colorTok and check ast.FuncType to differentiate the interface method and other functions. This problem may be solved.

### PR DESCRIPTION
**Pull request by hitzhangjie**
Explicitly check ast.File to emit the package colorTok, and check ast.FuncType to find the function name position accurately. By this way, dlv can avoid emitting the colorToks which of them may contains startPos=0 and endPos=7 which lets linewriter outputs dup `package` string in list command.

fix #2896

### CODE REVIEW

**Review by aarzilli — COMMENTED** [review]
There is a problem with this patch, if you print your colorization example in full you'll see that the `func` keyword is never highlighted. I've taken a look at it seems to me that the problem is actually caused by some ast.FuncType nodes that have the Func pos set to token.NoPos, I think emit shouldn't be called when kwpos == token.NoPos.
Aside from removing the mispelled "Pacakge" from the list (not replacing it, just removing it), it should be the only thing that's needed to fix this problem.

Also your test is failing on Windows.

File: pkg/terminal/colorize/colorize_test.go [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+	}
+
+	// ensures the AST analysis behaves as expected,
+	// please update `printed` if `terminal/colorize.Print` changes.
+	buf := &bytes.Buffer{}
+	colorize.Print(buf, "main.go", bytes.NewBuffer(dat), 1, 30, 10, colors)
+
+	colorize.Print(os.Stdout, "main.go", bytes.NewBuffer(dat), 1, 30, 10, colors)
+
+	if !reflect.DeepEqual(buf.Bytes(), printed) {
```
Comment (aarzilli) [inline pkg/terminal/colorize/colorize_test.go:89]: bytes.Equal or just `buf.String() == string(printed)`

File: pkg/terminal/colorize/colorize_test.go [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+	if err != nil {
+		t.Fatalf("read test fixture error: %v", err)
+	}
+
+	// ensures the AST analysis behaves as expected,
+	// please update `printed` if `terminal/colorize.Print` changes.
+	buf := &bytes.Buffer{}
+	colorize.Print(buf, "main.go", bytes.NewBuffer(dat), 1, 30, 10, colors)
+
+	colorize.Print(os.Stdout, "main.go", bytes.NewBuffer(dat), 1, 30, 10, colors)
```
Comment (aarzilli) [inline pkg/terminal/colorize/colorize_test.go:87]: Either remove this line or guard it with a check:

```
const printToStdout = false
if printToStdout {
    colorize.Print(os.Stdout, ...)
}
```

**Comment by hitzhangjie** [comment]
> There is a problem with this patch, if you print your colorization example in full you'll see that the `func` keyword is never highlighted. I've taken a look at it seems to me that the problem is actually caused by some ast.FuncType nodes that have the Func pos set to token.NoPos, I think emit shouldn't be called when kwpos == token.NoPos. Aside from removing the mispelled "Pacakge" from the list (not replacing it, just removing it), it should be the only thing that's needed to fix this problem.
> 
> Also your test is failing on Windows.

@aarzilli Thanks very much.

I misunderstood part of the code. The code wants to highlight the keyword, like 'func'. Now my commited patch highlight the function name, though my patch's purpose is to remove the dup `package` string. 

I have tested just removing  the "Package" and that's not enough. It will generate a `colorTok{token.Illegal, 0, 7}` which will be output as `package` by linewriter. Because of this, I add the `switch case *ast.FuncType` branch. 

I'll modify it and test it later.

File: pkg/terminal/colorize/colorize.go [hunk 3]
```diff
@@ -126,7 +141,7 @@ func Print(out io.Writer, path string, reader io.Reader, startLine, endLine, arr
 			emit(tokval.Interface().(token.Token), tokposval.Interface().(token.Pos), token.NoPos)
 		}
 
-		for _, kwname := range []string{"Case", "Begin", "Defer", "Pacakge", "For", "Func", "Go", "Interface", "Map", "Return", "Select", "Struct", "Switch"} {
+		for _, kwname := range []string{"Case", "Begin", "Defer", "Package", "For", "Func", "Go", "Interface", "Map", "Return", "Select", "Struct", "Switch"} {
```
[the remark this answers is not in the document]
Comment (hitzhangjie) [reply pkg/terminal/colorize/colorize.go]: Remove the  "Package".

done

File: pkg/terminal/colorize/colorize.go [hunk 4]
```diff
@@ -78,20 +79,34 @@ func Print(out io.Writer, path string, reader io.Reader, startLine, endLine, arr
...
 			return true
 		}
 
-		switch n := n.(type) {
+		switch n := node.(type) {
+		case *ast.File:
+			emit(token.PACKAGE, f.Package, token.NoPos)
+			return true
+		case *ast.FuncType:
+			// this implies `node` is a method of interface
```
[the remark this answers is not in the document]
Comment (hitzhangjie) [reply pkg/terminal/colorize/colorize.go]: I may misunderstand `ast.FuncType.Func==token.NoPos`, before I thought only a method of interface could satisfy this condition.

Here we should highlight the keyword `func` ranther than the function name. So when `n.Pos() == token.NoPos` we just return, otherwise `emits(token.Func, n.Pos, token.NoPos)` to hightlight the keyword `func`.

File: pkg/terminal/colorize/colorize_test.go (hunk 2 above)
Comment (hitzhangjie) [reply pkg/terminal/colorize/colorize_test.go]: done

File: pkg/terminal/colorize/colorize.go [hunk 5]
```diff
@@ -78,20 +79,34 @@ func Print(out io.Writer, path string, reader io.Reader, startLine, endLine, arr
...
 	for _, cgrp := range f.Comments {
 		for _, cmnt := range cgrp.List {
 			emit(token.COMMENT, cmnt.Pos(), cmnt.End())
 		}
 	}
 
-	ast.Inspect(f, func(n ast.Node) bool {
-		if n == nil {
+	ast.Inspect(f, func(node ast.Node) bool {
+		if node == nil {
```
[the remark this answers is not in the document]
Comment (hitzhangjie) [reply pkg/terminal/colorize/colorize.go]: done

File: pkg/terminal/colorize/colorize_test.go (hunk 1 above)
Comment (hitzhangjie) [reply pkg/terminal/colorize/colorize_test.go]: done

**Comment by hitzhangjie** [comment]
The Aggregator (Delve) -- TeamCity build failed for:
- linux/amd64/go1.17
- windows/amd64/go1.18
- windows/amd64/tip

I'll check go1.17/go1.18. Please tell me what does the "tip" means?

**Comment by aarzilli** [comment]
> The Aggregator (Delve) -- TeamCity build failed for:
> 
>     * linux/amd64/go1.17
> 
>     * windows/amd64/go1.18
> 
>     * windows/amd64/tip
> 
> 
> I'll check go1.17/go1.18. Please tell me what does the "tip" mean?

The failure on linux is probably unrelated, tip just means go built at master.

File: pkg/terminal/colorize/colorize.go [hunk 6]
```diff
@@ -92,6 +90,15 @@ func Print(out io.Writer, path string, reader io.Reader, startLine, endLine, arr
 		}
 
 		switch n := n.(type) {
+		case *ast.File:
+			emit(token.PACKAGE, f.Package, token.NoPos)
+			return true
+		case *ast.FuncType:
```
Comment (aarzilli) [inline pkg/terminal/colorize/colorize.go:96]: Remove this case and change the code:

```
				kwpos, ok := kwposval.Interface().(token.Pos)
				if ok {
					emit(token.ILLEGAL, kwpos, token.NoPos)
}
```

to say `if ok && kwpos != token.NoPos`

Comment (hitzhangjie) [reply pkg/terminal/colorize/colorize.go]: case *ast.FuncType is removed, and the code mentioned above is changed.

done

**Comment by aarzilli** [comment]
Note that the test still fails on Windows.

**Comment by aarzilli** [comment]
> Note that the test still fails on Windows.

My guess is that you are reading the input from a file on disk and git will convert line endings to crlf on windows, which will make the output not match the recorded output. 

Also "vehical" is spelled "vehicle".

**Comment by hitzhangjie** [comment]
> > Note that the test still fails on Windows.
> 
> My guess is that you are reading the input from a file on disk and git will convert line endings to crlf on windows, which will make the output not match the recorded output.
> 
> Also "vehical" is spelled "vehicle".



> > Note that the test still fails on Windows.
> 
> My guess is that you are reading the input from a file on disk and git will convert line endings to crlf on windows, which will make the output not match the recorded output.
> 
> Also "vehical" is spelled "vehicle".

I just installed a windows 10 in my parallels desktop. I'll test this problem.

**Review by aarzilli — APPROVED** [review]
LGTM

**Review by derekparker — APPROVED** [review]
LGTM
