### PR TITLE
pkg,service: add cmd `examinemem`(`x`) for examining memory.

### LINKED ISSUE #1584: Could delve inspect goroutine stack frame layout?
I want to list golang stack frame memory layout for diving into golang runtime。and noticed that gdb can inspect memory layout.

I list all delve commands with `help`, and test them one by one, but failed to find which I want.

can delve do it? or any plan about this? 

thank you

### PR DESCRIPTION
**Pull request by chainhelen**
According to #1800 #1584 #1038, `dlv` should enable the user to dive into
memory. User can print binary data in specific memory address range.
But not support for sepecific variable name or structures temporarily.(Because
I have no idea that modify `print` command.)  

Close #1584.

Next some questions: 
1. support the format for `print`cmd, include `address` , `variable name` and `structures`(no idea).  
2. support the form about `t(binary), f(float), a(address), i(instruction), c(char), s(string)` .  
3. support the negative position from address. (This is why also use `x /<FMT> [address]` like gdb, but not `x -<FMT> [address]`).  

----
I can close this pr if you against.

### CODE REVIEW

**Comment by aarzilli** [comment]
See test failures.

**Comment by chainhelen** [comment]
Sorry for test failures of docs, I have done.
(Something faield with others now, not involved with this pr.)

File: service/debugger/debugger.go [hunk 1]
```diff
@@ -1310,6 +1310,16 @@ func (d *Debugger) ListDynamicLibraries() []api.Image {
...
 }
 
+// ExamineMemory returns a list of specific address memory that len is num.
+func (d *Debugger) ExamineMemory(address uintptr, num int) ([]byte, error) {
+	d.processMutex.Lock()
+	defer d.processMutex.Unlock()
+
+	thread := d.target.CurrentThread()
+
+	return proc.ExamineMemory(thread, address, num)
```
Comment (aarzilli) [inline service/debugger/debugger.go]: `proc.ExamineMemory` is only used here, it should be inlined here instead of being a separate function.

File: service/rpc2/server.go [hunk 2]
```diff
@@ -731,3 +731,26 @@ func (s *RPCServer) ListDynamicLibraries(in ListDynamicLibrariesIn, out *ListDyn
 	out.List = s.debugger.ListDynamicLibraries()
 	return nil
 }
+
+// ExamineMemoryIn holds the arguments of ExamineMemory
+type ExamineMemoryIn struct {
+	Num     int
```
Comment (aarzilli) [inline service/rpc2/server.go]: I'd prefer Count or Size instead of Num

File: service/rpc2/server.go [hunk 3]
```diff
@@ -731,3 +731,26 @@ func (s *RPCServer) ListDynamicLibraries(in ListDynamicLibrariesIn, out *ListDyn
...
+	Address uintptr
+}
+
+// ExaminedMemoryOut holds the return values of ExamineMemory
+type ExaminedMemoryOut struct {
+	Address uintptr
+	MemData []byte
```
Comment (aarzilli) [inline service/rpc2/server.go]: Either Mem or Data instead of MemData.

File: service/rpc2/server.go [hunk 4]
```diff
@@ -731,3 +731,26 @@ func (s *RPCServer) ListDynamicLibraries(in ListDynamicLibrariesIn, out *ListDyn
...
+
+// ExamineMemoryIn holds the arguments of ExamineMemory
+type ExamineMemoryIn struct {
+	Num     int
+	Address uintptr
+}
+
+// ExaminedMemoryOut holds the return values of ExamineMemory
+type ExaminedMemoryOut struct {
+	Address uintptr
```
Comment (aarzilli) [inline service/rpc2/server.go]: This has to be the same as the input address so it doesn't need to be sent back.

File: pkg/terminal/command.go [hunk 5]
```diff
@@ -368,6 +369,19 @@ Defines <alias> as an alias to <command> or removes an alias.`},
 	
 If locspec is omitted edit will open the current source file in the editor, otherwise it will open the specified location.`},
 		{aliases: []string{"libraries"}, cmdFn: libraries, helpMsg: `List loaded dynamic libraries`},
+
+		{aliases: []string{"examinemem", "x"}, cmdFn: examineMemoryCmd, helpMsg: `Examine memory: x /[<FMT>] ADDRESS.
```
Comment (aarzilli) [inline pkg/terminal/command.go]: 1. This description makes it look like the '/' should always be included, i.e. that to use the default for FMT you should type `x / ADDRESS`. 
2. It should use the full name of the command (`examinemem`) instead of `x` for the syntax.
3. To be consistent with the way we describe syntax elsewhere both FMT and ADDRESS should be lowercase and inside angular parenthesis.
4. We don't use a `/` for options anywhere else, it should be a `-` (I get it that it's following gdb syntax but I would prefer internal consistency to external consistency).

File: service/debugger/debugger.go (hunk 1 above)
Comment (chainhelen) [reply service/debugger/debugger.go]: Done

File: service/rpc2/server.go (hunk 2 above)
Comment (chainhelen) [reply service/rpc2/server.go]: Done

File: service/rpc2/server.go (hunk 3 above)
Comment (chainhelen) [reply service/rpc2/server.go]: Done

File: service/rpc2/server.go (hunk 4 above)
Comment (chainhelen) [reply service/rpc2/server.go]: Done

File: pkg/terminal/command.go (hunk 5 above)
Comment (chainhelen) [reply pkg/terminal/command.go]: Done

File: service/debugger/debugger.go [hunk 6]
```diff
@@ -1310,6 +1310,23 @@ func (d *Debugger) ListDynamicLibraries() []api.Image {
 	return r
 }
 
+// ExamineMemory returns a list of specific address memory that len is num.
```
Comment (derekparker) [inline service/debugger/debugger.go]: This comment should be rewritten to something like: `ExamineMemory returns the raw memory stored at the given address. The amount of data to be read is specified by `length`. This function will return an error if it reads less than ``length`` bytes.`

File: service/debugger/debugger.go [hunk 7]
```diff
@@ -1310,6 +1310,23 @@ func (d *Debugger) ListDynamicLibraries() []api.Image {
...
+func (d *Debugger) ExamineMemory(address uintptr, count int) ([]byte, error) {
```
Comment (derekparker) [inline service/debugger/debugger.go]: s/count/length/ .. I think we use `size` internally in `proc/mem.go` as well, but I think either works a bit btter than `count`.

File: service/debugger/debugger.go [hunk 8]
```diff
@@ -1310,6 +1310,23 @@ func (d *Debugger) ListDynamicLibraries() []api.Image {
...
+	d.processMutex.Lock()
+	defer d.processMutex.Unlock()
+
+	thread := d.target.CurrentThread()
+	data := make([]byte, count)
+	rn, err := thread.ReadMemory(data, address)
```
Comment (derekparker) [inline service/debugger/debugger.go]: s/rn/read/ for a bit more descriptive name.

File: pkg/terminal/command.go [hunk 9]
```diff
@@ -1341,6 +1355,148 @@ func edit(t *Term, ctx callContext, args string) error {
...
+func parseFmtStr(fmtStr string) (count int, format byte, size int, err error) {
+	if len(fmtStr) <= 2 {
+		return 0, ' ', 0, fmt.Errorf("invalid argument for fmt")
+	}
+	if fmtStr[0] != '-' {
+		return 0, ' ', 0, fmt.Errorf("the first letter of fmt should be \"-\"")
+	}
+	i := 1
+	for ; i < len(fmtStr); i++ {
+		if fmtStr[i] < '0' || fmtStr[i] > '9' {
```
Comment (derekparker) [inline pkg/terminal/command.go]: Could use `unicode.IsDigit` here.

File: pkg/terminal/command.go [hunk 10]
```diff
@@ -368,6 +369,19 @@ Defines <alias> as an alias to <command> or removes an alias.`},
 	
 If locspec is omitted edit will open the current source file in the editor, otherwise it will open the specified location.`},
 		{aliases: []string{"libraries"}, cmdFn: libraries, helpMsg: `List loaded dynamic libraries`},
+
+		{aliases: []string{"examinemem", "x"}, cmdFn: examineMemoryCmd, helpMsg: `Examine memory: examinemem [-<fmt>] <address>.
+	Fmt is a count followed by a format letter and a size letter.
```
Comment (derekparker) [inline pkg/terminal/command.go]: I wonder if we could just simplify this. Do we really need to specify byte vs halfword vs word etc...?

I'm leaning towards not giving control over chunk size and simply having flags for `-len` and `-fmt`. Length is always in bytes and maybe defaults to the arch pointer size and fmt defaults to hex.

Comment (chainhelen) [reply pkg/terminal/command.go]: Oh, thx for your guidance. I get something, and need some time to change it.

**Comment by chainhelen** [comment]
Examine memory:

    examinemem [-fmt <format>] [-len <length>] <address>

Format represents the data format and the value is one of this list (default hex): oct(octal), hex(hexadecimal), dec(decimal), bin(binary).
Length is the number of bytes (default 1), please ensure len is not more than 1k.
Address is the memory location of the target to examine.
For example:  x -fmt hex -len 20 0xc00008af38

-------- 

Has done and rebase , please check it again. Thx.

**Comment by chainhelen** [comment]
Sorry for ci failed, it is because I add binary format. It looks diffrent versions of golang output this  differently. I will fix it.

File: pkg/terminal/command.go [hunk 11]
```diff
@@ -1341,6 +1351,175 @@ func edit(t *Term, ctx callContext, args string) error {
 	return cmd.Run()
 }
 
+func parseFmtStr(fmtStr string) (count int, format byte, size int, err error) {
```
Comment (aarzilli) [inline pkg/terminal/command.go]: This doesn't get called anymore.

File: pkg/terminal/command.go [hunk 12]
```diff
@@ -1341,6 +1351,175 @@ func edit(t *Term, ctx callContext, args string) error {
...
+	})
+	if len(v) != 1 && len(v) != 3 && len(v) != 5 {
+		return fmt.Errorf("wrong arguments for input")
+	}
+	// Default value
+	format := "hex"
+	length := 1
+	addressStr := v[len(v)-1]
+
+	StringArrIndex := func(strArr []string, str string) int {
```
Comment (aarzilli) [inline pkg/terminal/command.go]: In principle this is fine, however it's also going to make adding new arguments unnecessarily complicated. Something like this is just as simple and more flexible:

```
for i := 0; i < len(v); i++ {
    switch v[i] {
    case "-fmt":
         i++
         // parse argument...
    case "-len":
         i++
         // parse argument...
    default:
         if i != len(v)-1 {
             return fmt.Errorf(...)
         }
         // parse argument...
    }
}
```

similar to parseStackArgs.

File: pkg/terminal/command.go [hunk 13]
```diff
@@ -1341,6 +1351,175 @@ func edit(t *Term, ctx callContext, args string) error {
...
+			return fmt.Errorf("len must be an positive integer")
+		}
+		if length <= 0 {
+			return fmt.Errorf("len must be an positive integer")
+		}
+	}
+
+	// TODO, maybe configured by user.
+	if length > 1000 {
+		return fmt.Errorf("len must be not more than 1k")
```
Comment (aarzilli) [inline pkg/terminal/command.go]: "len must be less than 1000"

File: service/api/prettyprint.go [hunk 14]
```diff
@@ -354,3 +355,42 @@ func (v *Variable) writeSliceOrArrayTo(buf io.Writer, newlines bool, indent stri
 
 	fmt.Fprint(buf, "]")
 }
+
+func PrettyExamineMemory(address uintptr, res []uint64, format byte) string {
+	cols := int(8)
```
Comment (aarzilli) [inline service/api/prettyprint.go]: cols is a constant if I'm not mistaken, so:

```
const cols = 8
```

File: service/api/prettyprint.go [hunk 15]
```diff
@@ -354,3 +355,42 @@ func (v *Variable) writeSliceOrArrayTo(buf io.Writer, newlines bool, indent stri
...
+	}
+	colFormat := "    %#-" + strconv.Itoa(maxColCharNum) + string(format)
+
+	lines := ""
+	for i := 0; i < rows; i++ {
+		lines += fmt.Sprintf("%#x:", address)
+		for j := 0; j < cols && i*cols+j < l; j++ {
+			curOutput := fmt.Sprintf(colFormat, res[i*cols+j])
+
+			// Diffrent versions of golang output differently if binanry.
```
Comment (aarzilli) [inline service/api/prettyprint.go]: s/binanry/binary/

File: pkg/terminal/command.go [hunk 16]
```diff
@@ -1341,6 +1351,175 @@ func edit(t *Term, ctx callContext, args string) error {
...
+	if err != nil {
+		return fmt.Errorf("convert address into uintptr type failed, %s", err)
+	}
+
+	memArea, err := t.client.ExamineMemory(uintptr(address), length)
+	if err != nil {
+		return err
+	}
+
+	res := make([]uint64, 0, length)
```
Comment (aarzilli) [inline pkg/terminal/command.go]: I think you can skip this copy and just pass memArea to PrettyExamineMemory.

File: pkg/terminal/command.go (hunk 13 above)
Comment (chainhelen) [reply pkg/terminal/command.go]: I use `not more than` because `length` belong to [1, 1000] instead of [1, 1000). 
So maybe "len must be less than or equal to 1000“ better, what's your options?

File: pkg/terminal/command.go (hunk 12 above)
Comment (chainhelen) [reply pkg/terminal/command.go]: Oh, it is brilliant, thx

File: pkg/terminal/command.go [hunk 17]
```diff
@@ -1341,6 +1349,84 @@ func edit(t *Term, ctx callContext, args string) error {
 	return cmd.Run()
 }
 
+func examineMemoryCmd(t *Term, ctx callContext, args string) error {
+	v := strings.FieldsFunc(args, func(c rune) bool {
+		return c == ' '
+	})
+	if len(v) != 1 && len(v) != 3 && len(v) != 5 {
```
Comment (aarzilli) [inline pkg/terminal/command.go]: This is not necessary anymore.

File: pkg/terminal/command.go [hunk 18]
```diff
@@ -1341,6 +1349,84 @@ func edit(t *Term, ctx callContext, args string) error {
...
+				"hex":         'x',
+				"hexadecimal": 'x',
+				"dec":         'd',
+				"decimal":     'd',
+				"bin":         'b',
+				"binary":      'b',
+			}
+			priFmt, ok = fmtMapToPriFmt[v[i]]
+			if !ok {
+				return fmt.Errorf("a wrong format argument followed with -fmt")
```
Comment (aarzilli) [inline pkg/terminal/command.go]: `fmt.Errorf("%q is not a valid format", v[i])`

File: pkg/terminal/command.go [hunk 19]
```diff
@@ -1341,6 +1349,84 @@ func edit(t *Term, ctx callContext, args string) error {
...
+	// Default value
+	priFmt := byte('x')
+	length := 1
+
+	for i := 0; i < len(v); i++ {
+		switch v[i] {
+		case "-fmt":
+			i++
+			if i >= len(v) {
+				return fmt.Errorf("a format must be followed with -fmt")
```
Comment (aarzilli) [inline pkg/terminal/command.go]: `"expected argument after -fmt"`

File: pkg/terminal/command.go [hunk 20]
```diff
@@ -1341,6 +1349,84 @@ func edit(t *Term, ctx callContext, args string) error {
...
+				"binary":      'b',
+			}
+			priFmt, ok = fmtMapToPriFmt[v[i]]
+			if !ok {
+				return fmt.Errorf("a wrong format argument followed with -fmt")
+			}
+		case "-len":
+			i++
+			if i >= len(v) {
+				return fmt.Errorf("a length must be followed with -len")
```
Comment (aarzilli) [inline pkg/terminal/command.go]: `"expected argument after -len"`

File: pkg/terminal/command.go [hunk 21]
```diff
@@ -1341,6 +1349,84 @@ func edit(t *Term, ctx callContext, args string) error {
...
+			if err != nil || length <= 0 {
+				return fmt.Errorf("len must be an positive integer")
+			}
+			// TODO, maybe configured by user.
+			if length > 1000 {
+				return fmt.Errorf("len must be less than or equal to 1000")
+			}
+		default:
+			if i != len(v)-1 {
+				return fmt.Errorf("wrong arguments for input")
```
Comment (aarzilli) [inline pkg/terminal/command.go]: `fmt.Errorf("unknown option %q", v[i])`

File: pkg/terminal/command.go [hunk 22]
```diff
@@ -1341,6 +1349,84 @@ func edit(t *Term, ctx callContext, args string) error {
...
+			// TODO, maybe we can support expression.
+			address, err = strconv.ParseInt(v[len(v)-1], 0, 64)
+			if err != nil {
+				return fmt.Errorf("convert address into uintptr type failed, %s", err)
+			}
+		}
+	}
+
+	if address == 0 {
+		return fmt.Errorf("wrong argument for input, please specify a address")
```
Comment (aarzilli) [inline pkg/terminal/command.go]: `fmt.Errorf("no address specified")`

File: service/api/prettyprint.go [hunk 23]
```diff
@@ -354,3 +355,53 @@ func (v *Variable) writeSliceOrArrayTo(buf io.Writer, newlines bool, indent stri
 
 	fmt.Fprint(buf, "]")
 }
+
+func PrettyExamineMemory(address uintptr, memArea []byte, format byte) string {
+	cols := 8
+	// Avoid one row that are too long for binary
```
Comment (aarzilli) [inline service/api/prettyprint.go]: `// Avoid emitting rows that are too long when using binary format`

**Comment by hengwu0** [comment]
> 1. support the format for `print`cmd, include `address` , `variable name` and `structures`(no idea).

If you are investigativing, please fix this error:
```sh
jim@localhost:~/test$ dlv exec ./A
Type 'help' for list of commands.
(dlv) p 123//9
123
(dlv)
```
The Exp:`123//9` should be en error actually.

**Comment by chainhelen** [comment]
> > 1. support the format for `print`cmd, include `address` , `variable name` and `structures`(no idea).
> 
> If you are investigativing, please fix this error:
> 
> ```shell
> jim@localhost:~/test$ dlv exec ./A
> Type 'help' for list of commands.
> (dlv) p 123//9
> 123
> (dlv)
> ```
> 
> The Exp:`123//9` should be en error actually.

I will do my best.
