### PR TITLE
proc: better handling of bad DW_TAG_inlined_subroutine without debug_line

### LINKED ISSUE #1720: Nil dereference during getting lineinfo from compilation unit
Got an error report from a GoLand user, unfortunatelly no steps to reproduce, debugger logs, or sources. Also the code was changed since then, but maybe it is still relevant/useful. They got the following error with delve build on revision a82e6d69875ed11a0bb3b80d15efba4b4722106e and go 1.12.9:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x42a467a]
     
    goroutine 5 [running]:
    github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMapsCompileUnit(0xc0000da500, 0xc0001764a0, 0xc000102630, 0xc0000a83f0, 0xc0021dc990)
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/bininfo.go:1473 +0x10ca
    github.com/go-delve/delve/pkg/proc.(*BinaryInfo).loadDebugInfoMaps(0xc0000da500, 0xc000102630, 0xc000414000, 0x17df84, 0x17df84, 0xc0000b7560, 0xc0000a8360)
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/bininfo.go:1316 +0x5ae
    created by github.com/go-delve/delve/pkg/proc.loadBinaryInfoMacho
        /opt/buildAgent/work/4c3e5e3eabfaf2d2/pkg/proc/bininfo.go:1120 +0x323

Reportedly update to go1.13.1 fixed the problem.

### PR DESCRIPTION
**Pull request by aarzilli**
```
proc: better handling of bad DW_TAG_inlined_subroutine without debug_line

Avoid crashing with nil pointer dereference, signal error instead.

Fixes #1720

```

### CODE REVIEW

File: pkg/dwarf/line/state_machine.go [hunk 1]
```diff
@@ -322,6 +322,10 @@ func (lineInfo *DebugLineInfo) LineToPC(filename string, lineno int) uint64 {
 
 // PrologueEndPC returns the first PC address marked as prologue_end in the half open interval [start, end)
 func (lineInfo *DebugLineInfo) PrologueEndPC(start, end uint64) (pc uint64, file string, line int, ok bool) {
+	if lineInfo == nil {
```
Comment (chainhelen) [inline pkg/dwarf/line/state_machine.go]: [smile, please forgive me for any offence]  
Excuse me, I have a doubt here. Program will be crashed if `lineInfo == nil`, so can not reach here.

Comment (aarzilli) [reply pkg/dwarf/line/state_machine.go]: [nil is a valid value for a pointer receiver](https://play.golang.org/p/ARKGhiFRrdi)
